### ISSUE TITLE
QG训练营网络组第一周周记：2016年4月17日

### ISSUE THREAD

**Issue by kimZLeung** [kimZLeung/kimZLeung#1]
# QG训练营网络组第一周周记：2016年4月17日

<br>
## 生活随记

> 对于这一周，我感觉自己很痛苦。我貌似从来没有试过这么充实生活如此丰富的一周。我这整整一周都被各大工作室的面试填满了。我还记得有一天晚上我舍友问我：今晚有空吗？我说不行啊我要去面试呢。舍友有点崩溃地说：你又去面试啊！！？没错。我这整整一周都游走在各个工作室的面试之间。从星期二的topview和研发到星期三的topview技术面。很累但是收获得也很多。说起面试其实我觉得还是QG的面试让我收获得比较多，虽然已经不是这周的内容了。但是我的的确确从QG的面试中看到了自己的弊端，我现在还常常想起那时候技术面试的自己的窘况。我从中看到了自己很多的不足，也将会去改正自己。
## 学习情况

> 上一周QG的技术面试让我感觉到自己的HTML和CSS还依然只是十分菜鸟的水平所以我这个星期除了学校的课程学习之外，主要的精力是放在了HTML和CSS的学习之上，我通过了入门平台W3School用每天的课余和面试过后的时间去学习HTML。我认为只有打好坚实的基础才能在后面的学习事半功倍。这个过程还是让我学到了挺多新鲜的有趣的标签和用法。感觉效果还是挺好的，只不过还是书本的知识比较系统化。
## 一周总结

> 其实我这一周的计划挺简单的。毕竟时间已经差不多被面试占满了。除开每天的上课和学习时间。我基本上就尽量利用了自己的空闲时间在看HTML和CSS。总的来说这一周学的东西不多。但是我要巩固好自己的基础，有底层才能搭起高楼。
## 存在问题

> 其实最大的问题还是学习效率的问题。学习的效率会因为自身在学习过程中的专注度而有所变化。换句话说就是我自己肯花时间，但是有时候的分心会让自己的效率降低。从而使自己学得少。还有一个就是时间分配的不合理。说来可能也是效率的问题。我是一件事情做完之后，常常发现时间不多了。以前不明显，但在面试接踵而来的这个星期，我的时间就显然变得不够用了。过多的时间花在一件事情上，使得自己的下一件事要做得更久，而我压迫了自己的睡眠时间，从而使第二天的精力也不，我必须跳出这个恶性循环。
## 下周规划

> 呃关于这个下周规划，其实我在昨天已经在tv那边听取了考核题目，所以我下周的计划大多都是围绕topview的考核来定的。可能作业质量难以保证但是我会尽力。下周我会利用我的大量课余时间在前半周看视频学习JAVA。然后我会利用一些晚上的空余时间来熟悉一下eclipse和体会JAVA与C的不同点。下半周我会开始花时间去构思一下我的作品。并且保持我的JAVA的学习进度。周末会参加QG的训练营和组内的训练。并尽量在当晚及时思考复习训练营的知识。

**Comment by ArtemisZ** [comment]
充实的一周，O(∩_∩)O哈哈~，好好习惯吧。
