### ISSUE TITLE
笔记和心得

### ISSUE THREAD

**Issue by kimZLeung** [kimZLeung/kimZLeung#2]
# 笔记
## MarkDown

> 是一种简易转化为HTML的语言，常用工具有印象笔记。
## Git和Github

> Git是一种储存仓库，从一开始的本地到后来的联网的集中，再发展到后来的分布式，有了本地和网上远程服务器端的仓库可以存储数据。本地Git的三个工作区域：工作目录，暂存区域，本地仓库。Github就是一种远程的仓库。
## google和百度

> 两个搜索引擎对比起来，Google的搜索效率会更加高一些。而百度更多的搜索结果可能会是重复复制的各种文本，拉低搜索效率。推荐的翻墙软件：GreenVPN，shadowsocks。
## 心得

>  通过这节课我了解到了Git和Github的概念，他们能更加系统地帮我们储存自己的文档或者代码。使自己用起来更加方便，就平时修改起来也比较方便。同时我们也有了解到了Google和百度的一些实际性的区别，更新了我之前对搜索引擎的概念吧。大家也踊跃地提出了很多问题，各方面都有，我也更加全面地理解到了Github的一些性质和分布式管理的一些优势。

**Comment by ArtemisZ** [comment]
Github还有很多很好玩的东西，我也还没摸索透呢，但是考核和训练营完了之后可以好好玩一下Github，而且Github上面有很多大牛的代码可以看哦。
