### ISSUE TITLE
QG训练营网络组第二周周记：2016年4月24日

### ISSUE THREAD

**Issue by kimZLeung** [kimZLeung/kimZLeung#3]
# QG训练营网络组第二周周记：2016年4月24日

<br>
## 生活随记

> 其实说随记...说真的我倒是觉得没什么好写的。当然只是针对这周而言。比起上一周，这周更加痛苦和难受。基本上每一天除了上课吃饭和睡觉，我都在看马士兵！！每一天晚上都是一碰枕头就能睡着。很累的同时我也在告诉自己：生活就是折腾。的确挺累的，前端的知识也放下了好久没碰过。java还挺好学的，但还是觉得自己喜欢做一些看得见的东西。特别是一直在学java的时候，能抽出一段时间来碰一下html和css，来完成这个小组的小作业，也是挺好的。虽然写得真的太随便了。但是我想说，当我在做网页的时候我是真的乐在其中的。
> ## 学习情况
> 
> 关于这周的学习情况。  
> 1、我认为自己的学习时间都花在了Java上面。就这周来说，我从周一开始就每天看视频学习Java。每天学一章左右。
>    2、从最开始的基本语法开始，这周我学习了Java的面向对象的思想，运行异常的处理，一些接口，继承的知识，还学习了容器和IO的一些知识。
>    3、学了这些之后我也尝试性地用eclipse去实现一下我学过的知识。并让这些知识得到了巩固。
> ## 一周总结
> 
> 关于这一周，我感觉收获还是挺多的。
> 1、不同于以往上课下课的生活，这整整一周我都在拼了命地学java，当然这十分辛苦。可是辛苦的背后也有了颇丰的收获。我了解到了许多以前不懂的问题。知道了以前不知道的思想和思考方式。甚至开始写一些以前想都没想过的比较繁杂的程序。我知道于我而言，这些都比较有益。 
> 2、关于这周来说。我总结只有一个字：苦。也许这也正是以后我要面对的生活，现在的辛苦大概也是为了以后更少碰壁吧，所以只能好好努力咯。
> ## 存在问题
> 
> 1、时间分配的不合理。不合理地分配时间让我学习的效率得不到提高。 
> 2、目标没确定好。具体来说就是本来我有一个目标，我学习效率自然就起来了，但是当我完成了这个目标之后，我下一个目标过于模糊而未知，让我的懒惰又支配了自己。
> 3、不重视休息。睡不好精神也难以集中，学习和写代码自然效率降低。必须注意休息。
## 下周规划

> 1、对于下周的规划。我首先还是得先把精力集中在考核任务上。我要分配大部分空闲时间，比如每天的晚上，来构思分析考核的项目。
> 2、对于这边的训练营可能难以顾全。我已经感受到了挺大的压力，尽量能完成任务就完成任务。

**Comment by ArtemisZ** [comment]
马士兵的Java啊。。我也好久没看这个了，如果只是简单地了解Java的语法的话马士兵的视频也是极好的，但是如果要深·入·了解的话可以问一下我们后台的师兄们哦，他们对Java有一番独特的见解 ^ - ^，时间分配的问题只能靠自己调哦，但是要注重效率，效率和时间不一定成正比的。
