### ISSUE TITLE
笔记和心得

### ISSUE THREAD

**Issue by kimZLeung** [kimZLeung/kimZLeung#4]
# 笔记
## 前端三利剑

> 就是我们常说的Html、Css和JavaScript。
## <!DOCTYPE>

> 关于现在的前端编程，一般是使用html5，，所以头部声明一般是使用<!DOCTYPE html>，我之前也不知道这个<!DOCTYPE>是干啥用的,听完才知道又忽略细节了
## 关于内联元素和块级元素

> 内联元素是不会占据一行的，而块级元素就会。而且块级元素可以改变宽度和高度还有各种各样Margin，padding的。而如果调整内联元素的margin属性的话，只能调整到左右的边距。
## 关于html的编程规范

> 关于xml，xml的书写规范比较严谨，标签必须要小写，而且<br />这类标签必须闭合。
## 关于编译器

> 我个人认为前端的轻量级编译器十分强大，更有各种功能强大的插件，这也是我比较喜欢前端的原因。个人在用sumbline text2，这个编译器的插件就是...十分牛逼。
## 关于布局

> 布局这个坑我也曾经跳过。哦不，其实一直没有上来过，用CSS布局真的有点难，比较可怕。经常会牵一发而动全身。而且那些float属性和每个浏览器的不同特点，更加增加了布局的难度。关于层模型和浮动模型...说多了都是泪。就不说了。反正就是很痛苦就是了。

**Comment by ArtemisZ** [comment]
编程规范的东西很重要的哦，我之前就一直跳在这个坑里，关于布局的知识推荐看《精通CSS》这本书，平时多做做一些网页练练手。
