### ISSUE TITLE
# QG训练营网络组第二周周记：2016年5月 1 日

### ISSUE THREAD

**Issue by kimZLeung** [kimZLeung/kimZLeung#5]
# QG训练营网络组第二周周记：2016年5月 1 日

<br>
## 生活随记

> 对不起这周的周记迟交了，有点感觉忙不过来了。这周我整个星期都在考虑着重构代码的思路，因为用了一些新的东西和一些比较隐蔽的错误，我搞了很久才重构完成，然后突然想起来我的周记还没弄好，于是现在急急忙忙来写周记咯。这周总的来说并没有什么变化，自从那边tv的考核开始之后，我每天都是忙碌在上课和构思怎么写这个项目之间。总会感觉有点力不从心，感觉事情依旧忙不过来。
## 学习情况

> 关于这周的学习情况。> 1、这周大部分时间花在了重构代码上，我认为自己距离那些大神来说还差很远，所以我只能靠自己去努力。可能花的时间太长都兼顾不过来了。  > 2、从重构方面也思考出了一些东西，并觉得对分包有了新的理解，对java有了一些新的理解 > 3、在写项目这方面也收获到了挺多的东西，慢慢学会了把小的东西加以组合变成大的东西。
## 一周总结

> 关于这一周，我感觉收获还是挺多的。> 1、首先我在这一周重构了自己的代码，几乎是以另一种方式重新写完了之前的功能和需求。重新分包的同时让自己收获到了更多java写项目的经验 ，体会到了一些后台的比较底层的东西和知识，起码也拓宽了自己的视野吧 > 2、目前存在的问题还有很多，我也还有很多没处理好的地方，希望能快点找到解决的办法吧。 >3、对于前端暂时还没有太多时间去学习，自己尝试性地看了一下js，感觉和java也还是有一些共通的地方的。
## 存在问题

> 1、已经不能说是时间分配的问题了，这周的时间太过紧，毕竟如果想专注于一边的话，另一边就真的挺难做好的。 > 2、因为时间不够充足，以想两边都顾及反而有点不利于自己的专注。 > 3、对于作业的完成我也挺惭愧的，也可能是平时没有把所以时间都腾给工作室的学习的关系吧。
## 下周规划

> 1、对于下周的规划。对于下周的规划，我可能还得腾出一点时间来复习基础的课程，因为准备要期中考试。 >2、考核的任务也不能落下，基本上是能做多少就做多少。只能尽力而为。

**Comment by ArtemisZ** [comment]
关于Java和JavaScript其实是有一段不得不说的渊源，你可以去找一下，但是从实际上这两者的相似度还没有Java和C#的相似度大哦，据说Java和C#的相似度高达80% ^-^。关于时间分配这个问题之前就说过了，在你做考核或者在做作业的时候其实就是在选择了。不过慢慢来，不急，自己的未来还是要自己去好好想的，加油↖(^ω^)↗。
PS，注意markdown的格式啊。
